CREATE DATABASE BookApp
GO

USE BookApp
GO

CREATE TABLE Books
(
	BookId INT PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	Author VARCHAR(50) NOT NULL,
	Publisher VARCHAR(50) NOT NULL,
	NoOfPages INT NOT NULL,
	Rating INT NOT NULL,
	Edition INT NOT NULL,
	Price INT NOT NULL,
	ReleaseDate DATE NOT NULL
)
GO

CREATE TABLE Categories
(
	CategoryId INT PRIMARY KEY IDENTITY(1,1),
	CategoryName VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Books_Categories
(
	BookId INT NOT NULL,
	CategoryId INT NOT NULL,
)
GO

ALTER TABLE Books_Categories ADD CONSTRAINT FK_Books FOREIGN KEY(BookId) REFERENCES Books(BookId)
GO
ALTER TABLE Books_Categories ADD CONSTRAINT FK_Categories FOREIGN KEY(CategoryId) REFERENCES Categories(CategoryId)
GO

CREATE TABLE States
(
	StateId INT PRIMARY KEY IDENTITY(1,1),
	StateName VARCHAR(50) NOT NULL	
)
GO

CREATE TABLE Cities
(
	CityId INT PRIMARY KEY IDENTITY(1,1),
	CityName VARCHAR(50) NOT NULL
)
GO

CREATE TABLE Customers
(
	CustId INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Contact BIGINT NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	AddressLine VARCHAR(100) NOT NULL,
	CityID INT NOT NULL,
	StateID INT NOT NULL
)
GO

ALTER TABLE Customers ADD CONSTRAINT FK_Cities FOREIGN KEY(CityId) REFERENCES Cities(CityId)
GO
ALTER TABLE Customers ADD CONSTRAINT FK_States FOREIGN KEY(StateId) REFERENCES States(StateId)